[project]
name = "lossviz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.5.0",
    "matplotlib>=3.10.0",
    "optax>=0.2.4",
]
